### ISSUE TITLE
Date in Payments table incorrect for Modulr connector

### ISSUE THREAD

**Issue by KL-Lib** [formancehq/stack#1147]
With the Modulr connector active, observe that all payments appear in the Payments table with the same Date:
![image](https://github.com/formancehq/stack/assets/97224363/4e67586a-e242-453f-9b53-17b80ffd4bcb)

But when you drill into the Payment it has the correct date listed.

**Comment by KL-Lib** [comment]
![image](https://github.com/formancehq/stack/assets/97224363/f852a8c1-a035-46d7-9b78-adaafd949fe6)

**Comment by flemzord** [comment]
Available in [v2.0.0-beta.14](https://github.com/formancehq/stack/releases/tag/v2.0.0-beta.14)
