### ISSUE TITLE
Tutorial doc for building new payment connector might be outdated

### ISSUE THREAD

**Issue by TamerB** [formancehq/stack#1396]
I was trying to build a new custom connector by following [this md](https://github.com/formancehq/stack/blob/main/components/payments/docs/tuto-connector.md), however, I found several issues with this tutorial doc which blocked my progress. They also gave me the impression that this doc is outdated and maybe incomplete. Here's a list of the main issues that I found:

- Couldn't find this `HTTPModule` in `cmd/root.go` and couldn't find this block anywhere in this repo:
```
cdi.ConnectorModule[stripe.Config, stripe.TaskDescriptor](
    viper.GetBool(authBearerUseScopesFlag),
    stripe.NewLoader(),
),
```
However, I found `HTTPModule` inside `cmd/connectors/internal/api/module.go` and found the following line in it:
```
addConnector[stripe.Config](stripe.NewLoader()),
```
So, I added `addConnector[example.Config](example.Loader),` too.
I also found that `connectorConfigsHandler()` in `cmd/connectors/internal/api/connectorconfigs.go` has `stripe.Config{},` in it so I add `example.Config{},` to.
- For `connectorConfigsHandler()`  to accept the changes, `Config` struct must implement `configtemplate.TemplateBuilder` interface. And for this to happen, the following must be added for `Config` struct:
```
func (c Config) ConnectorName() string {
	return name.String()
}

func (c Config) Marshal() ([]byte, error) {
	return json.Marshal(c)
}

func (c Config) BuildTemplate() (string, configtemplate.Config) {
	cfg := configtemplate.NewConfig()

	cfg.AddParameter("name", configtemplate.TypeString, name.String(), false)

	return name.String(), cfg
}
```
- The following logs are not accurate:
```
payments-payments-1  | time="2022-07-01T09:12:21Z" level=info msg="Restoring state" component=connector-manager provider=example
payments-payments-1  | time="2022-07-01T09:12:21Z" level=info msg="Not installed, skip" component=connector-manager provider=example

```
The logs I found were similar to this:
```
payments-connectors-1  | time="2024-04-07T03:55:31Z" level=info msg="Restoring state for all connectors" component=connector-manager provider=example
```
- After following the tutorial and adding the changes above and running `docker compose up`, I found that:
    - Running `curl http://localhost:8080/connectors/stripe -X POST` returns `Bad Gateway`.
    - Running `curl http://localhost:8080/api/payments/connectors/stripe -X POST` succeeded.
    - Running `curl http://localhost:8080/api/payments/connectors/example -X POST`  returned `{"errorCode":"INTERNAL","errorMessage":"installing connector: install connector: pq: invalid input value for enum connector_provider: \"example\""`.

**Comment by paul-nicolas** [comment]
It seems you are on the v1.10 version of the documentation. For the v2 version of payment, you can find the documentation to create a connector here: https://docs.formance.com/next/payments/get-started/connectors/framework

**Comment by TamerB** [comment]
Thanks for updating the docs.

Can you please check the following comments on the updated docs:

- The URL that is working is still `http://localhost:8080/api/payments/connectors/example` not `http://localhost:8080/connectors/example`.
- Schedule option `OPTIONS_RUN_INDEFINITELY` doesn't exist. The available schedule options are:
    - `OPTIONS_RUN_NOW`
    - `OPTIONS_RUN_IN_DURATION`
    - `OPTIONS_RUN_PERIODICALLY`
    - `OPTIONS_RUN_NOW_SYNC`
    - `OPTIONS_RUN_SCHEDULED_AT`
- `IngestPayments` accepts `(ctx context.Context, batch PaymentBatch)` (2 arguments) as input, but in docs it accepts 4 arguments. And `curl` fails after adding `IngestPayments` with 2 arguments.

**Comment by paul-nicolas** [comment]
Hello again sorry for the late reply ! As we discussed on slack, I've fixed all your comments and did a pass on the framework doc to ensure its correctness.
