### ISSUE TITLE
How to avoid applying the same payment twice

### ISSUE THREAD

**Issue by juanpmarin** [formancehq/stack#1464]
Hi, this project looks awesome!

I couldn't find a method in the documentation to prevent the same transaction from being applied twice. Here's the use case:

I use an external payment gateway, and payments are received via a webhook. For various reasons, my endpoint might be called twice by the gateway for the same transaction.

Is there a way to assign a unique identifier in the performance ledger so that a duplicate transaction would fail with a descriptive error?

**Comment by flemzord** [comment]
Hello @juanpmarin 

You can use the idempotency key for this :) The Ledger will refuse any key already used in the Ledger

https://docs.formance.com/next/api#tag/Ledger/operation/v2CreateTransaction

**Comment by juanpmarin** [comment]
Awesome, thanks!
