### ISSUE TITLE
Dockerfile error on amd64 server architecture

### ISSUE THREAD

**Issue by hakimzuldev** [formancehq/stack#434]
The Dockerfile on line 17 returned error as ARCH=$(dpkg --print-architecture) gives amd64 value. As per checking with https://github.com/F1bonacc1/process-compose/releases/tag/v0.51.4, they do not have amd64.tar.gz. Instead, they have x86_64.

Perhaps the Dockerfile can be fixed.

**Comment by flemzord** [comment]
@hakimzuldev I've just pushed a modification that should solve the problem. 
Can you pull main and tell me if it works for you?

**Comment by hakimzuldev** [comment]
It works when I run `docker compose up -d`. Thank you @flemzord
